apiVersion: v2
name: github-sts
description: GitHub Security Token Service (STS) - OIDC to GitHub token exchange
type: application
version: 1.0.0
appVersion: 0.0.1
keywords:
  - github
  - oidc
  - authentication
  - security
  - sts
  - token-exchange
home: https://github.com/Depthmark/github-sts-helm
sources:
  - https://github.com/Depthmark/github-sts-helm
  - https://github.com/Depthmark/github-sts
