---
name: Release Please

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions: {}

jobs:
  release-please:
    name: Release Please
    runs-on: ['self-hosted', 'talos']
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    outputs:
      helm_release_created: ${{ steps.release.outputs['charts/github-sts--release_created'] }}
      helm_tag_name: ${{ steps.release.outputs['charts/github-sts--tag_name'] }}
    steps:
      - uses: Depthmark/github-sts-action@main
        id: sts
        with:
          sts-url: https://github-sts-dev.adelisle.com
          scope: Depthmark-Lab/test-release-helm
          identity: release
          app: depthmark-release-bot
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ steps.sts.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json